<a href="https://colab.research.google.com/github/maxashoka3/prac-Pytorch/blob/main/Pytroch_lession_day_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# checking the gpu
! nvidia-smi


Sat Jan 20 07:59:15 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   54C    P8              10W /  70W |      0MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

## PY Torch Fundamentals


In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


In [ ]:
print(torch.__version__)

2.1.0+cu121


## Tensor

### Creating tensor

In [ ]:
# creating scalar torch
scalar =  torch.tensor(8)
scalar

tensor(8)

In [ ]:
# get tensor back as python int
scalar.item()

8

In [ ]:
# vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
## Matrix
matrix = torch.tensor([[7,8],
                       [6,7]])
matrix

tensor([[7, 8],
        [6, 7]])

In [ ]:
matrix.shape

torch.Size([2, 2])

In [ ]:
matrix.ndim

2

In [ ]:
matrix[1]

tensor([6, 7])

In [ ]:
# Tensor
tensor = torch.tensor([[[3,2,5],
                        [5,6,8],
                        [2,4,5],
                       ]])
tensor.ndim

3

In [ ]:
# testig the homogenous datatypes
homo  = torch.tensor(["y","g"])
homo

ValueError: too many dimensions 'str'

In [ ]:
tensor.ndim

3

In [ ]:
tensor.shape

torch.Size([1, 3, 3])

In [ ]:
tensor[0][2]

tensor([2, 4, 5])

In [ ]:
a = torch.tensor[[4]]

TypeError: 'builtin_function_or_method' object is not subscriptable

In [ ]:
tensor = torch.tensor([[4
                       ]])
tensor.ndim

2

In [ ]:
tensor =  torch.tensor([[[[[[[[5]]]]]]]])


### Random tensors
why rangom tensors?
Random tensor are important becuase the way many neural networks learn is that they start with tensors full of random numbers and then adjust random number to bette represent the dataclass_transform
`Start with random numbers -> look at data -> update random number -> look at hte data -> pdate random number

In [ ]:
# Create a random tensor of shape(3,4)
random_tensor = torch.rand(1,3,4)
random_tensor

tensor([[[0.7522, 0.3914, 0.1993, 0.8884],
         [0.3960, 0.6880, 0.5931, 0.5025],
         [0.3449, 0.5436, 0.6980, 0.7182]]])

In [ ]:
random_tensor.ndim

3

In [ ]:
# Create a random tensor of shape(3,4)
random_tensor = torch.rand(10,10,10)
random_tensor

tensor([[[3.3534e-01, 6.0064e-01, 4.2634e-01, 5.3164e-01, 8.4548e-01,
          7.1656e-01, 1.3037e-01, 4.8036e-01, 5.1009e-01, 1.1230e-01],
         [9.7683e-01, 9.6131e-01, 6.3000e-01, 7.5590e-01, 2.8986e-01,
          5.9904e-01, 6.4150e-01, 5.0701e-01, 3.1124e-01, 9.7206e-01],
         [3.5782e-01, 7.2534e-01, 8.6973e-01, 8.9044e-02, 9.0081e-01,
          3.1419e-01, 7.4670e-01, 3.7101e-01, 3.7558e-01, 4.6334e-01],
         [2.1567e-01, 1.1586e-01, 2.5694e-01, 3.6182e-02, 1.5456e-02,
          3.5527e-01, 1.5535e-01, 3.6676e-01, 4.8144e-01, 9.3099e-02],
         [6.6741e-01, 5.6337e-01, 6.2832e-01, 5.0539e-02, 4.5230e-01,
          3.8614e-01, 4.8461e-02, 7.8102e-01, 2.0445e-01, 7.5708e-01],
         [6.4701e-01, 9.2691e-01, 9.3196e-01, 4.9956e-01, 8.8981e-02,
          6.1847e-01, 3.6465e-01, 3.0799e-01, 8.5999e-01, 8.1741e-01],
         [6.3874e-01, 4.2950e-01, 5.1022e-01, 6.5372e-01, 5.2721e-01,
          4.7783e-01, 3.0456e-01, 7.2055e-01, 5.7532e-01, 4.4227e-01],
         [3.7

In [ ]:
random_tensor.ndim

3

In [ ]:
# create a random tensor with similar shape to an image tensor
random_image_size_tensor= torch.rand(size = (224, 224,3))# height, width, colr channel(R,G,B)
random_image_size_tensor.shape,random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

#### Zeros and ones

In [ ]:
zeros = torch.zeros(size  =  (3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
zeros = torch.ones(size  =  (3,4,4,5))
zeros

In [ ]:
zeros.ndim

4

In [ ]:
zeros.shape

torch.Size([3, 4, 4, 5])

In [ ]:
zeros.shape

torch.Size([3, 4, 4, 5])

In [ ]:
# using torch
torch.arange(1,11)

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
one_to_ten = torch.arange(start=1,end = 40, step= 3)

In [ ]:
ten_zeros = torch.zeros_like(input = one_to_ten)

In [ ]:
ten_zeros
zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
ten_zeros = torch.zeros_like(input = zeros)
ten_zeros

#### Tensor datatypes

` Majro datatypes error in the 3 big errors we will run into with pythorch`
* Tesor not right datatypes
* Tensor not right shape
* Tensors not right device

In [ ]:
float_32_tensor  = torch.tensor([3.0,6.0,9.0],
                                dtype = None,
                                device = None,
                                requires_grad = False)

In [ ]:
int_32_tensor = torch.tensor([3,6,9],
                             dtype = torch.long)
int_32_tensor

tensor([3, 6, 9])

In [ ]:
int_32_tensor*torch.tensor([3,6,9],
                           dtype = torch.long)

tensor([ 9, 36, 81])

#### Getting informaiton from tensors
1. Tensors not right datatypee --------tensor.dtype
2. Tensors not right shapr----------- tensor.shape

3. Tensors not in right device - ---------- - - -- tensor.device

In [ ]:
print(f"Datatypes of tensor: {int_32_tensor.dtype}")
print(f"Shape of tensor: {int_32_tensor.shape}")
print(f"Device of tensor: {int_32_tensor.device}")

Datatypes of tensor: torch.int64
Shape of tensor: torch.Size([3])
Device of tensor: cpu


#### Manipulating Tensors (tensor operations)
Tensor operations include:
* Addition
* Substraction
* Multiplicaiton (element-wise)
* Division
* Matrix multiplication

In [ ]:
# Create a tensor
# addition
tensor = torch.tensor([1,2,3])
tensor, tensor+10

(tensor([1, 2, 3]), tensor([11, 12, 13]))

In [ ]:
# Multiplicaiton
tensor = torch.tensor([1,2,3])
tensor, tensor * 10

(tensor([1, 2, 3]), tensor([10, 20, 30]))

In [ ]:
# Multiplicaiton

tensor, tensor -1

(tensor([1, 2, 3]), tensor([0, 1, 2]))

In [ ]:
# Multiplicaiton

tensor, tensor / 2

(tensor([1, 2, 3]), tensor([0.5000, 1.0000, 1.5000]))